import { Insight, Startup } from "./types";

export const startups: Startup[] = [
  { id: "linear", name: "Linear", websiteUrl: "https://linear.app", tagline: "The purpose-built system for product development.", description: "A product development platform built for modern software teams.", tags: ["Productivity", "B2B", "Developer tools"], status: "tracking", color: "#5E6AD2", initials: "L", lastActivity: "Today", pricing: [{ name: "Free", price: "$0", cadence: "per member / month", detail: "For small teams getting started." }, { name: "Basic", price: "$8", cadence: "per member / month", detail: "For growing product teams." }, { name: "Business", price: "$16", cadence: "per member / month", detail: "Advanced security and admin controls.", highlighted: true }] },
  { id: "attio", name: "Attio", websiteUrl: "https://attio.com", tagline: "The CRM of the future.", description: "A flexible, collaborative customer relationship platform for modern teams.", tags: ["CRM", "Sales", "B2B"], status: "tracking", color: "#171717", initials: "A", lastActivity: "Yesterday", pricing: [{ name: "Free", price: "$0", cadence: "per user / month", detail: "For individuals and small teams." }, { name: "Plus", price: "$29", cadence: "per user / month", detail: "For scaling customer operations.", highlighted: true }, { name: "Pro", price: "$69", cadence: "per user / month", detail: "For complex GTM teams." }] },
  { id: "granola", name: "Granola", websiteUrl: "https://granola.so", tagline: "The AI notepad for people in back-to-back meetings.", description: "Meeting intelligence that turns your notes into useful context.", tags: ["AI", "Productivity", "Meetings"], status: "watching", color: "#DB6A43", initials: "G", lastActivity: "2 days ago", pricing: [{ name: "Free", price: "$0", cadence: "per month", detail: "Core notes and meeting capture." }, { name: "Business", price: "$14", cadence: "per user / month", detail: "Unlimited history and team features.", highlighted: true }] },
  { id: "clay", name: "Clay", websiteUrl: "https://clay.com", tagline: "Go to market with unique data — and the ability to act on it.", description: "Data enrichment and outbound workflow platform for GTM teams.", tags: ["Sales", "Data", "AI"], status: "tracking", color: "#E98955", initials: "C", lastActivity: "4 days ago", pricing: [{ name: "Explorer", price: "$149", cadence: "per month", detail: "For individual GTM builders." }, { name: "Pro", price: "$800", cadence: "per month", detail: "For revenue teams at scale.", highlighted: true }] },
  { id: "pocus", name: "Pocus", websiteUrl: "https://pocus.com", tagline: "The AI Revenue Platform for GTM teams.", description: "AI-powered prospecting and sales workflow tools.", tags: ["Sales", "AI", "Revenue"], status: "watching", color: "#7B55E8", initials: "P", lastActivity: "6 days ago", pricing: [{ name: "Growth", price: "Custom", cadence: "annual plan", detail: "For high-performing GTM teams.", highlighted: true }] }
];

export const insights: Insight[] = [
  { id: "i1", startupId: "linear", type: "pricing", headline: "Linear increased its Business plan price by 33%.", summary: "The Business tier moved from $12 to $16 per member/month. Linear also introduced advanced guest access and SCIM provisioning as Business-only capabilities.", createdAt: "Today, 09:24", impact: "High impact" },
  { id: "i2", startupId: "attio", type: "positioning", headline: "Attio is leaning into the AI-native CRM narrative.", summary: "The homepage hero now leads with “The AI-native CRM for the next era of business,” replacing its previous message focused on data flexibility.", createdAt: "Yesterday, 16:40", impact: "Medium impact" },
  { id: "i3", startupId: "granola", type: "feature", headline: "Granola launched a shared team workspace.", summary: "The new Team Workspace lets users search across shared meeting notes and automatically surfaces decisions, owners, and follow-up items.", createdAt: "Aug 12, 10:15", impact: "High impact" },
  { id: "i4", startupId: "clay", type: "pricing", headline: "Clay added a lower-entry Explorer plan.", summary: "A new $149/month Explorer tier sits below the existing Pro offering, making its enrichment workflows accessible to smaller outbound teams.", createdAt: "Aug 11, 13:05", impact: "Medium impact" },
  { id: "i5", startupId: "linear", type: "feature", headline: "Linear added native customer-request insights.", summary: "The product page now highlights AI-generated themes from customer feedback, positioned as a shortcut from signals to roadmap decisions.", createdAt: "Aug 8, 11:30", impact: "Medium impact" }
];

export const getStartup = (id: string) => startups.find((startup) => startup.id === id);
export const getInsightsForStartup = (id: string) => insights.filter((insight) => insight.startupId === id);
