import Link from "next/link";
import { ArrowLeftIcon, ArrowTopRightOnSquareIcon, BellAlertIcon, CheckIcon } from "@heroicons/react/24/outline";
import { notFound } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { InsightCard } from "@/components/insight-card";
import { StartupAvatar } from "@/components/startup-avatar";
import { Tag } from "@/components/tag";
import { getInsightsForStartup, getStartup } from "@/lib/mock-data";

export default function StartupProfilePage({ params }: { params: { id: string } }) { const startup = getStartup(params.id); if (!startup) notFound(); const companyInsights = getInsightsForStartup(startup.id); return <AppShell><div className="mx-auto max-w-6xl px-5 py-7 sm:px-8"><Link href="/startups" className="inline-flex items-center gap-1.5 text-sm font-semibold text-slate hover:text-ink"><ArrowLeftIcon className="h-4 w-4" />All startups</Link><header className="mt-6 flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div className="flex gap-4"><StartupAvatar startup={startup} size="lg" /><div><div className="flex flex-wrap items-center gap-3"><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">{startup.name}</h1><span className="inline-flex items-center gap-1.5 text-xs font-medium text-emerald-600"><i className="h-2 w-2 rounded-full bg-emerald-500" />Tracking</span></div><p className="mt-1 max-w-xl text-sm leading-6 text-slate">{startup.tagline}</p><div className="mt-3 flex flex-wrap gap-1.5">{startup.tags.map((tag) => <Tag key={tag}>{tag}</Tag>)}</div></div></div><div className="flex gap-2"><a className="button-secondary" href={startup.websiteUrl} target="_blank" rel="noreferrer">Website <ArrowTopRightOnSquareIcon className="h-4 w-4" /></a><button className="button-primary"><BellAlertIcon className="h-4 w-4" />Alert me</button></div></header><div className="mt-9 grid gap-8 lg:grid-cols-[minmax(0,1fr)_320px]"><section><div><p className="eyebrow">Change history</p><h2 className="mt-1 text-xl font-bold">Insight timeline</h2></div><div className="mt-4 space-y-3">{companyInsights.length ? companyInsights.map((insight) => <InsightCard insight={insight} key={insight.id} />) : <div className="panel p-8 text-center text-sm text-slate">No signals detected yet.</div>}</div></section><aside><section className="panel overflow-hidden"><div className="border-b bg-slate-50 px-5 py-4"><p className="eyebrow">Current pricing</p><p className="mt-1 text-sm text-slate">Last checked today</p></div><div className="divide-y">{startup.pricing.map((plan) => <div key={plan.name} className="p-5"><div className="flex items-baseline justify-between"><p className="font-semibold">{plan.name}</p><p className="text-right font-bold">{plan.price}<span className="block text-[11px] font-normal text-slate">{plan.cadence}</span></p></div><p className="mt-2 text-sm leading-5 text-slate">{plan.detail}</p>{plan.highlighted && <span className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-radar"><CheckIcon className="h-3.5 w-3.5" />Key tier</span>}</div>)}</div></section><section className="panel mt-4 p-5"><p className="eyebrow">Positioning snapshot</p><p className="mt-3 text-sm leading-6 text-slate">{startup.description}</p><p className="mt-4 border-t pt-4 text-xs text-slate">Source: homepage and pricing page · Updated today</p></section></aside></div></div></AppShell>; }
