import { BellIcon, ChevronDownIcon, PlusIcon } from "@heroicons/react/24/outline";
import { AppShell } from "@/components/app-shell";
import { InsightCard } from "@/components/insight-card";
import { StatCard } from "@/components/stat-card";
import { insights } from "@/lib/mock-data";

export default function DashboardPage() { return <AppShell><div className="mx-auto max-w-6xl px-5 py-7 sm:px-8"><header className="flex items-center justify-between"><div><p className="eyebrow">Tuesday, August 15</p><h1 className="mt-1 text-2xl font-bold tracking-tight sm:text-3xl">Your competitive radar</h1></div><div className="flex items-center gap-2"><button className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 bg-white text-slate hover:text-ink"><BellIcon className="h-5 w-5" /></button><button className="button-primary hidden sm:inline-flex"><PlusIcon className="h-4 w-4" />Add competitor</button></div></header><section className="mt-7 grid gap-3 sm:grid-cols-3"><StatCard label="Changes detected" value="24" change="18% this week" /><StatCard label="High-impact signals" value="6" change="2 new today" /><StatCard label="Companies tracked" value="148" change="12 added this month" /></section><section className="mt-9 grid gap-8 lg:grid-cols-[minmax(0,1fr)_240px]"><div><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="eyebrow">Latest changes</p><h2 className="mt-1 text-xl font-bold">Radar feed</h2></div><button className="button-secondary py-2 text-xs">All activity <ChevronDownIcon className="h-4 w-4" /></button></div><div className="mt-4 space-y-3">{insights.map((insight) => <InsightCard key={insight.id} insight={insight} />)}</div></div><aside className="hidden lg:block"><div className="panel p-5"><p className="eyebrow">Signal mix · 30 days</p><div className="mt-5 space-y-4"><Meter label="Pricing" value="42%" width="42%" color="bg-amber-400" /><Meter label="Feature launches" value="35%" width="35%" color="bg-emerald-500" /><Meter label="Positioning" value="23%" width="23%" color="bg-violet-500" /></div></div><div className="mt-4 rounded-2xl bg-ink p-5 text-white"><p className="text-sm font-semibold">Never miss a move</p><p className="mt-1 text-sm leading-5 text-slate-300">Get high-impact signals in your inbox every Monday.</p><button className="mt-4 text-sm font-semibold text-indigo-300 hover:text-white">Manage alerts →</button></div></aside></section></div></AppShell>; }

function Meter({ label, value, width, color }: { label: string; value: string; width: string; color: string }) { return <div><div className="mb-1.5 flex justify-between text-sm"><span>{label}</span><span className="text-slate">{value}</span></div><div className="h-1.5 rounded-full bg-slate-100"><div className={`h-full rounded-full ${color}`} style={{ width }} /></div></div>; }
